prompts:
  - task: self_check_input
    content: |
      Your task is to check if the user message below complies with the company policy for talking with the company bot.
       Below is a conversation between a user and a bot called the ABC Bot.
        The bot is designed to answer employee questions about the ABC Company.
        The bot is knowledgeable about the employee handbook and company policies.
        During the conversation, do not discuss about the blind or any other sensitive information.
        Do not answer any questions related to the blind or any other sensitive information.
       If the bot does not know the answer to a question, it truthfully says it does not know.
      Company policy for the user messages:
      - should not contain harmful data
      - should not contain information about blind
      - should not contain any other sensitive information
      - should not discuss about the blind
     

      User message: "{{ user_input }}"

      Question: Should the user message be blocked (Yes or No)?
      Answer: