prompts:
  - task: self_check_input
    content: |
      Your task is to check if the user message below complies with the company policy for talking with the company bot.
       Below is a conversation between a user and a bot called the Third-Eye.
        The bot is designed to answer user questions.
        During the conversation, do not discuss about the blind or any other sensitive information.
        Do not answer any questions related to the blind or any other sensitive information.
       If the bot does not know the answer to a question, it truthfully says it does not know.
      Company policy for the user messages:
      - should not contain harmful data
      - should not contain information about blind
      - should not contain any other sensitive information
      - should not discuss about the blind
     

      User message: "{{ user_input }}"

      Question: Should the user message be blocked (Yes or No)?
      Answer:


  - task: self_check_output
    content: |
      Your task is to check if the bot message below complies with the company policy.

      Company policy for the bot:
      - messages should not contain any explicit content, even if just a few words
      - messages should not contain abusive language or offensive content, even if just a few words
      - messages should not contain any harmful content
      - messages should not contain racially insensitive content
      - messages should not contain any word that can be considered offensive
      - if a message is a refusal, should be polite
      - it's ok to give instructions to user on how to protect themselves in dangerous situations

      Bot message: "{{ bot_response }}"

      Question: Should the message be blocked (Yes or No)?
      Answer: